var svg=d3.select("body").append("svg").attr({id:"mainsvg",width:1400,height:660}),fileList="WikiNews Huffington CrooksAndLiars EmptyWheel Esquire FactCheck VIS_papers IMDB PopCha Cards_PC Cards_Fries QuantumComputing".split(" "),initialDataset="EmptyWheel",categories=["person","location","organization","miscellaneous"],fileName,opacity,layerPath,maxFreq,spinner,axisGroup=svg.append("g").attr("id","axisGroup"),xGridlinesGroup=svg.append("g").attr("id","xGridlinesGroup"),mainGroup=svg.append("g").attr("id",
    "main"),legendGroup=svg.append("g").attr("id","legend");addDatasetsOptions();function addDatasetsOptions(){for(var d=document.getElementById("datasetsSelect"),m=0;m<fileList.length;m++){var f=fileList[m],c=document.createElement("option");c.textContent=f;c.value=f;c["data-image"]="images2/datasetThumnails/"+fileList[m]+".png";d.appendChild(c)}document.getElementById("datasetsSelect").value=initialDataset;fileName=document.getElementById("datasetsSelect").value;loadData()}
function loadData(){var d=document.getElementById("loadingSpinner");spinner=(new Spinner({lines:25,length:15,width:5,radius:25,color:"#000",speed:2,trail:50,className:"spinner"})).spin(d);fileName="data/"+fileName+".tsv";0<=fileName.indexOf("Cards_Fries")?(categories=["increases_activity","decreases_activity"],loadAuthorData(draw,initTop)):0<=fileName.indexOf("Cards_PC")?(categories="adds_modification removes_modification increases decreases binds translocation".split(" "),loadAuthorData(draw,initTop)):
    0<=fileName.indexOf("PopCha")?(categories=["Comedy","Drama","Action","Fantasy","Horror"],loadAuthorData(draw,initTop)):0<=fileName.indexOf("IMDB")?(categories=["Comedy","Drama","Action","Family"],loadAuthorData(draw,initTop)):0<=fileName.indexOf("VIS")?(categories=["Vis","VAST","InfoVis","SciVis"],loadAuthorData(draw,initTop)):0<=fileName.indexOf("QuantumComputing")?(fileName="data/"+fileName+".tsv",categories=["Unknown citation","Have citation","Affiliations","Author"],initTop=15,loadQuantumComputing(draw,
        initTop)):0<=fileName.indexOf("Huffington")?(categories=["person","location","organization","miscellaneous"],loadBlogPostData(draw,initTop),document.getElementById("rel").checked=!0):(categories=["person","location","organization","miscellaneous"],loadBlogPostData(draw,initTop))}
function loadNewData(d){legendGroup.selectAll("*").remove();axisGroup.selectAll("*").remove();xGridlinesGroup.selectAll("*").remove();mainGroup.selectAll("*").remove();fileName=this.options[this.selectedIndex].text;document.getElementById("rel").checked=!1;loadData()}
function draw(d){function m(){var b,k=mainGroup.selectAll(".word").data(p,function(a){return a.id});k.exit().remove();k.enter().append("g").attr({transform:function(a){return"translate("+a.x+", "+a.y+")rotate("+a.rotate+")"}}).attr("class","word").append("text").text(function(a){return a.text}).attr({id:function(a){return a.id},"class":"textData","font-family":"Arial","font-size":function(a){return a.fontSize},fill:function(a,b){return color(categories.indexOf(a.topic))},"fill-opacity":function(a){return opacity(a.sudden)},
    "text-anchor":"middle","alignment-baseline":"middle",topic:function(a){return a.topic},visibility:function(a){return a.placed?"visible":"hidden"}});k.transition().duration(800).attr({transform:function(a){return"translate("+a.x+", "+a.y+")rotate("+a.rotate+")"}}).select("text").attr("font-size",function(a){return a.fontSize}).attr({visibility:function(a){return a.placed?"visible":"hidden"}});mainGroup.selectAll(".connection").on("mouseover",function(){var a=d3.select(this);a.style("cursor","crosshair");
    var b=mainGroup.select("#"+a[0][0].__data__.sourceID),c=b.attr("fill"),h=mainGroup.select("#"+a[0][0].__data__.targetID),x=h.attr("fill");a.attr("stroke-width",4);b.attr({stroke:c,fill:c,"stroke-width":1.5});h.attr({stroke:x,fill:x,"stroke-width":1.5})});mainGroup.selectAll(".connection").on("mouseout",function(){var a=d3.select(this);a.style("cursor","crosshair");var b=mainGroup.select("#"+a[0][0].__data__.sourceID),c=mainGroup.select("#"+a[0][0].__data__.targetID);a.attr("stroke-width",t(a[0][0].__data__.weight));
    b.attr({stroke:"none","stroke-width":0});c.attr({stroke:"none","stroke-width":0})});mainGroup.selectAll(".textData").on("mouseenter",function(){var a=d3.select(this);a.style("cursor","pointer");b=a.attr("fill");var c=a.text(),n=a.attr("topic");mainGroup.selectAll(".textData").filter(function(a){return a&&a.text===c&&a.topic===n}).attr({stroke:b,"stroke-width":1})});mainGroup.selectAll(".textData").on("mouseout",function(){var a=d3.select(this);a.style("cursor","default");var b=a.text(),c=a.attr("topic");
    mainGroup.selectAll(".textData").filter(function(a){return a&&!a.cloned&&a.text===b&&a.topic===c}).attr({stroke:"none","stroke-width":"0"})});mainGroup.selectAll(".textData").on("click",function(){var a=d3.select(this),c=a.text(),n=a.attr("topic");a=mainGroup.selectAll(".textData").filter(function(a){return a&&a.text===c&&a.topic===n});var h=[];d3.select("path[topic='"+n+"']")[0][0].__data__.forEach(function(a){h.push({x:a.x,y0:a.y0+a.y,y:0})});a[0].forEach(function(a){var b=a.__data__,c=b.fontSize,
    k=h[b.timeStep+1];k.y=-b.streamHeight;b=a.cloneNode(!0);d3.select(b).attr({visibility:"visible",stroke:"none","stroke-size":0});var r=a.parentNode.cloneNode(!1);r.appendChild(b);a.parentNode.parentNode.appendChild(r);d3.select(r).attr({cloned:!0,topic:n}).transition().duration(300).attr({transform:function(a,b){return"translate("+k.x+","+(k.y0+k.y-c/2)+")"}})});h[0].y=h[1].y;h[h.length-1].y=h[h.length-2].y;y.append("path").datum(h).attr("d",u).style("fill",b).attr({"fill-opacity":b,stroke:"black",
    "stroke-width":.3,topic:n,wordStream:!0});mainGroup.selectAll(".textData").filter(function(a){return a&&!a.cloned&&a.topic===n}).attr("visibility","hidden")});v.forEach(function(a){d3.select("path[topic='"+a+"']").on("click",function(){mainGroup.selectAll(".textData").filter(function(b){return b&&!b.cloned&&b.placed&&b.topic===a}).attr({visibility:"visible"});document.querySelectorAll("g[cloned='true'][topic='"+a+"']").forEach(function(a){a.parentNode.removeChild(a)});document.querySelectorAll("path[wordStream='true'][topic='"+
    a+"']").forEach(function(a){a.parentNode.removeChild(a)})})});legendGroup.attr("transform","translate("+c.left+","+(q+c.top+10)+")");k=legendGroup.selectAll("g").data(g.topics).enter().append("g").attr("transform",function(a,b){return"translate(10,"+12*b+")"});k.append("circle").attr({r:5,fill:function(a,b){return color(b)},"fill-opacity":1,stroke:"black","stroke-width":.5});k.append("text").text(function(a){return a}).attr({"font-size":12,"alignment-baseline":"middle",dx:8});spinner.stop()}var f=
    12*categories.length,c={left:20,top:20,right:10,bottom:30},e=globalWidth-(c.left+c.top),q=globalHeight-(+c.top+c.bottom+10+f),b=d3.layout.wordStream().size([e,q]).fontScale(d3.scale.linear()).minFontSize(globalMinFont).maxFontSize(globalMaxFont).data(d).flag(globalFlag),g=b.boxes();d=b.minSud();var z=b.maxSud();maxFreq=b.maxFreq();svg.transition().duration(300).attr({width:globalWidth,height:globalHeight});var u=d3.svg.area().interpolate("cardinal").x(function(b){return b.x}).y0(function(b){return b.y0}).y1(function(b){return b.y0+
    b.y}),w=[];g.data.forEach(function(b){w.push(b.date)});b=d3.scale.ordinal().domain(w).rangeBands([0,e]);b=d3.svg.axis().orient("bottom").scale(b);axisGroup.attr("transform","translate("+c.left+","+(q+c.top+10+f)+")");b=axisGroup.call(b);styleAxis(b);b=d3.scale.ordinal().domain(d3.range(0,w.length+1)).rangeBands([0,e+e/g.data.length]);b=d3.svg.axis().orient("bottom").scale(b);xGridlinesGroup.attr("transform","translate("+(c.left-e/g.data.length/2)+","+(q+c.top+10+f+c.bottom)+")");f=xGridlinesGroup.call(b.tickSize(-q-
    10-f-c.bottom,0,0).tickFormat(""));styleGridlineNodes(f);mainGroup.attr("transform","translate("+c.left+","+c.top+")");var y=mainGroup.append("g").attr("id","wordStreamG");f=d3.svg.line().x(function(b){return b.x}).y(function(b){return b.y}).interpolate("cardinal");e=[];for(b=0;b<g.layers[0].length;b++){var l=Object.assign({},g.layers[0][b]);l.y=l.y0;e.push(l)}for(b=g.layers[g.layers.length-1].length-1;0<=b;b--)l=Object.assign({},g.layers[g.layers.length-1][b]),l.y+=l.y0,e.push(l);b=e.length;f=f(e.slice(0,
    b/2))+"L"+f(e.slice(b/2,b)).substring(1,f(e.slice(b/2,b)).length)+"Z";var v=g.topics;e=mainGroup.selectAll(".curve").data(g.layers);e.exit().remove();e.enter().append("path").attr("d",u).style("fill",function(b,c){return color(c)}).attr({"class":"curve","fill-opacity":0,stroke:"black","stroke-width":0,topic:function(b,c){return v[c]}});e.attr("d",u).style("fill",function(b,c){return color(c)}).attr({"fill-opacity":0,stroke:"black","stroke-width":0,topic:function(b,c){return v[c]}});layerPath=mainGroup.selectAll("path").append("path").attr("d",
    f).attr({"fill-opacity":0,"stroke-opacity":0});var p=[];d3.map(g.data,function(b){g.topics.forEach(function(c){p=p.concat(b.words[c])})});allW=JSON.parse(JSON.stringify(p));opacity=d3.scale.log().domain([d,z]).range([.4,1]);var t;0<=fileName.indexOf("Huffington")?d3.json("data/linksHuff2012.json",function(b,c){var a=c.filter(function(a){return 5<a.weight}),e=document.getElementById("rel").checked;a.forEach(function(a){a.sourceID=a.sourceID.split(".").join("_").split(" ").join("_");a.targetID=a.targetID.split(".").join("_").split(" ").join("_")});
    var d=[];a.forEach(function(a){var b=p.find(function(b){return b.id===a.sourceID&&!0===b.placed}),c=p.find(function(b){return b.id===a.targetID&&!0===b.placed});void 0!==b&&void 0!==c&&d.push({sourceX:b.x,sourceY:b.y,targetX:c.x,targetY:c.y,weight:a.weight,sourceID:a.sourceID,targetID:a.targetID,id:a.sourceID+"_"+a.targetID})});t=d3.scale.linear().domain(d3.extent(d,function(a){return a.weight})).range([.5,3]);opacScale=d3.scale.linear().domain(d3.extent(d,function(a){return a.weight})).range([.5,
        1]);a=mainGroup.selectAll(".connection").data(d,function(a){return a.id});a.exit().remove();a.enter().append("line").attr("class","connection");a.transition().duration(800).attr("opacity",e?1:0).attr({x1:function(a){return a.sourceX},y1:function(a){return a.sourceY},x2:function(a){return a.targetX},y2:function(a){return a.targetY},stroke:"#444444","stroke-opacity":function(a){return opacScale(a.weight)},"stroke-width":function(a){return t(a.weight)}});m()}):m()}
function styleAxis(d){d.selectAll(".domain").attr({fill:"none"});d.selectAll(".tick line").attr({fill:"none"});d.selectAll(".tick text").attr({"font-family":"serif","font-size":15})}function styleGridlineNodes(d){d.selectAll(".domain").attr({fill:"none",stroke:"none"});d.selectAll(".tick line").attr({fill:"none","stroke-width":.7,stroke:"lightgray"})};